name: Fairfax County Real Estate Forecast
description: Dual-mode application for forecasting Fairfax County real estate values with visual dashboards and AI-powered insights.
author: Fairfax County Analytics Team
specification_version: 1.0
prototype_version: 3.0
date: "2026-01-14"

runtimes:
  - editor: JupyterLab
    kernel: Python 3.13
    edition: Standard

environment_variables:
  AZURE_OPENAI_ENDPOINT:
    default: ""
    description: "Azure OpenAI endpoint (e.g., https://your-resource.openai.azure.com/)"
    prompt_user: true
  AZURE_OPENAI_API_KEY:
    default: ""
    description: "Azure OpenAI API key (will use mock chatbot if not provided)"
    prompt_user: true
  AZURE_OPENAI_DEPLOYMENT:
    default: "gpt-4o"
    description: "Azure OpenAI model deployment name"
    prompt_user: false
  AZURE_OPENAI_API_VERSION:
    default: "2024-02-15-preview"
    description: "Azure OpenAI API version"
    prompt_user: false

tasks:
  - type: run_session
    name: Install Dependencies
    short_summary: Install Python packages and dependencies
    long_summary: Installs Prophet, Streamlit, Plotly, and Azure OpenAI SDK. Requires 4GB memory, takes 3-5 minutes.
    cpu: 2
    memory: 4
    kernel: python3
    script: scripts/install_dependencies.py

  - type: run_session
    name: Validate Environment
    short_summary: Validate setup and configuration
    long_summary: Validates dependencies, CSV files, and environment readiness for deployment.
    cpu: 1
    memory: 2
    kernel: python3
    script: scripts/setup_environment.py

  - type: run_session
    name: Train Initial Models
    short_summary: Train forecasting models for top districts
    long_summary: Trains Prophet models for top 5 districts by property value. Provides immediate forecasting capability. Takes 5-10 minutes.
    cpu: 2
    memory: 8
    kernel: python3
    script: scripts/train_initial_models.py

  - type: start_application
    name: Fairfax Real Estate Forecast
    subdomain: fairfax-forecast
    script: apps/launch.py
    short_summary: Launch the Fairfax County Real Estate Forecast application
    long_summary: Launches dual-mode Streamlit app with dashboard (60%) and AI assistant (40%). Provides forecasts, risk analysis, and strategic insights.
    cpu: 2
    memory: 4
    kernel: python3